version: 2

models:
  - name: stg_mental_health
    description: "Staging model for CDC mental health indicators"
    columns:
      - name: state
        tests:
          - not_null
      - name: metric_percentage
        tests:
          - not_null

  - name: fct_mental_health_indicators
    description: "Final fact table for dashboarding"
    columns:
      - name: state
        tests:
          - not_null
      - name: indicator
        tests:
          - not_null

  - name: dim_locations
    description: "Dimension table for geographic locations"
    columns:
      - name: state_name
        tests:
          - not_null
          - unique